services:
  red:
    build:
      context: .
      target: red-runtime
    volumes:
      - simdata:/data
    environment:
      - DB_PATH=/data/sim.db
      - BLUE_TEAM_URL=http://blue:8081
    ports:
      - "8082:8082"
  

  blue:
    build:
      context: .
      target: blue-runtime
    volumes:
      - simdata:/data
    environment:
      - DB_PATH=/data/sim.db
    ports:
      - "8081:8081"
      

  dashboard:
    build:
      context: .
      target: dashboard-runtime
    volumes:
      - simdata:/data
    environment:
      - DB_PATH=/data/sim.db
    ports:
      - "8080:8080"
    depends_on:
      - red
      - blue

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-runtime
    ports:
      - "3000:80"
    depends_on:
      - dashboard
      - red
      - blue

volumes:
  simdata: